openmrs/openmrs-module-emrapi

- omod/src/main/resources/config.xml
This global property wasn't migrated from the PIH/openmrs-module-emr, but is used in the EMRAPI getextraidentifiers method. It's also used in the coreapps patient header to display multiple identifiers.
The discussion is available in the dev forum https://groups.google.com/a/openmrs.org/forum/#!topic/dev/s6M719M6loM
> Adding emr.extraPatientIdentifierTypes Global Property

- api/src/main/java/org/openmrs/module/emrapi/diagnosis/Diagnosis.java
- api/src/main/java/org/openmrs/module/emrapi/visit/VisitDomainWrapper.java
- api/src/test/java/org/openmrs/module/emrapi/visit/VisitDomainWrapperTest.java
@djazayeri , can you have a look at this?   The boolean parameters probably aren't needed, but I wasn't sure if we were intentionally excluding secondary diagnoses on all of the places we want to use this, so I added it in for more flexibility.  We can remove it if you don't like it...
> Add method to VisitDomainWrapper to get only unique diagnoses

- api/src/main/java/org/openmrs/module/emrapi/encounter/ConceptMapper.java
- api/src/test/java/org/openmrs/module/emrapi/encounter/ConceptMapperTest.java
1) If short name is not available for a concept in a locale use its fully specified name in that locale
2) If fully specified name is also not available in that locale, use short name name of that concept in the system default locale
3) If short name is not available for the system default locale, use its fully specified name
> Correct fallback of concept names in a locale

- api/src/test/java/org/openmrs/module/emrapi/encounter/DateMapperTest.java
- omod/pom.xml
- pom.xml
This test just fails with Java 7, see
https://issues.openmrs.org/browse/EA-76?focusedCommentId=236199&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-236199
modified:   api/src/test/java/org/openmrs/module/emrapi/encounter/DateMapperTest.java
No more depency on distro 2.3.
modified:   omod/pom.xml
modified:   pom.xml
> EA-76: Ignore DateMapperTest and quit depending on distro.

- condition-list/src/main/java/org/openmrs/module/emrapi/conditionslist/contract/ConditionMapper.java
- condition-list/src/test/java/org/openmrs/module/emrapi/conditionslist/contract/ConditionMapperTest.java
When user is logged in with a locale for which condition concept does not have a name, ConditionHistory api throws NullPointerException.
Issue: [EA-124](https://issues.openmrs.org/browse/EA-124)
> ConditionHistory api throws null pointer exception when a different locale is used

- api/src/main/java/org/openmrs/module/emrapi/diagnosis/CodedOrFreeTextAnswer.java
The PR adds CodedOrFreeTextAnswer constructor to support `CodedOrFreeTextAnswer(Concept codedAnswer, ConceptName specificCodedAnswer, String nonCodedAnswer)`.
see https://issues.openmrs.org/browse/TRUNK-5343
> TRUNK-5343: Add CodedOrFreeTextAnswer constructor to support coreapps-api-2.2 functionality

- omod/src/test/java/org/openmrs/module/emrapi/web/controller/BaseEmrControllerTest.java
`BaseEmrControllerTest` is currently `@Ignore`'d and should simply be a base abstract for all context-sensitive tests to subclass.
See [here](https://github.com/openmrs/openmrs-module-emrapi/blob/a49c1311c40c742a6563bc0b88dd42c0526eec18/omod/src/test/java/org/openmrs/module/emrapi/web/controller/BaseEmrControllerTest.java#L32-L33).
> EA-137: Making BaseEmrControllerTest abstract.

- api/src/main/java/org/openmrs/module/emrapi/EmrApiConstants.java
- api/src/main/java/org/openmrs/module/emrapi/EmrApiProperties.java
- api/src/test/java/org/openmrs/module/emrapi/EmrApiPropertiesTest.java
- omod/src/main/java/org/openmrs/module/emrapi/web/controller/EmrConceptSearchController.java
- omod/src/main/resources/config.xml
introduced global propery 'emrapi.conceptSourcesForDiagnosisSearch'. Updated EmrApiProperties.getConceptSourcesForDiagnosisSearch() to read from global property and fetch matching reference term sources. updated test.
> EA-130: Allowing diagnosis concept searches against source(s) defined through global property

- api-2.2/pom.xml
- api-2.2/src/main/java/openmrs/module/emrapi/diagnosis/MigrateDiagnosis.java
- api-2.2/src/test/java/org/openmrs/emrapi/diagnosis/MigrateDiagnosisTest.java
- api-2.2/src/test/java/org/openmrs/emrapi/diagnosis/OldDiagnosisBuilder.java
- api-2.2/src/test/resources/DiagnosisDataset.xml
- api/src/main/java/org/openmrs/module/emrapi/db/EmrVisitDAO.java
- api/src/main/java/org/openmrs/module/emrapi/db/EmrVisitDAOImpl.java
- api/src/main/java/org/openmrs/module/emrapi/test/builder/ObsBuilder.java
- api/src/main/java/org/openmrs/module/emrapi/visit/EmrVisitService.java
- api/src/main/java/org/openmrs/module/emrapi/visit/EmrVisitServiceImpl.java
- api/src/main/resources/hql/patients_diagnoses.hql
- api/src/main/resources/messages.properties
- omod/src/main/java/org/openmrs/module/emrapi/extension/html/AdminList.java
- omod/src/main/java/org/openmrs/module/emrapi/web/controller/MigrateDiagnosisController.java
- omod/src/main/resources/config.xml
- omod/src/main/webapp/encounterDiagnosisMigrationDashboard.jsp
- pom.xml
Ticket : https://issues.openmrs.org/browse/TRUNK-5342
Added support for Migrating Encounter Diagnosis data to their new table.
This is only possible if one is running platform 2.2.
> Trunk-5342 : Migrating Encounter Diagnosis data to the new encounter_diagnosis table prior platform 2.2.

- web-2.2/pom.xml
- web-2.2/src/main/java/org/openmrs/module/emrapi/web/controller/ConditionController.java
Ticket : https://issues.openmrs.org/browse/RA-1641
added a handler to return all Conditions
> RA-1641: inactive conditions should be displayed

- api/src/main/java/org/openmrs/module/emrapi/adt/AdtServiceImpl.java
https://issues.openmrs.org/browse/RA-950
I did the following
1.Enabled adding a past visit with a start date but no end date
2.But disabled adding a past visit with a start date but no end date if this would overlap with another existing visit
3.Enabled editing a closed visit and remove its end date
4.But disabled editing a closed visit and remove its end date if this would overlap with another existing visit
Other changes are in core-apps https://github.com/openmrs/openmrs-module-coreapps/pull/275
> RA-950: Add LastVisit and EditVisit require an EndDate

- api/src/main/java/org/openmrs/module/emrapi/encounter/EncounterDomainWrapper.java
- api/src/test/java/org/openmrs/module/emrapi/encounter/EncounterDomainWrapperTest.java
JIRA Issue: https://issues.openmrs.org/browse/EA-153
This is a pretty trivial bug-fix with a test case added.
> EA-153: NullPointerException in EncounterDomainWrapper when Encounter datetime is null

- api/src/main/java/org/openmrs/module/emrapi/EmrApiConstants.java
- omod/src/test/resources/diagnosisMetaData.xml
**Changes I did** 
Corrected the EMR Api Constants to make them consistent with db.
Reason : For MySQL, the collation is utf8_general_ci that is case insensitive so case does not matter but in other dbs like PostgreSQL we need to match the case correctly while searching for concept by concept name.
**Link to ticket** 
https://issues.openmrs.org/browse/EA-159
> EA-159 Correct EMR Api Constants to make them consistent with db

- api/src/main/resources/hql/visit_primary_diagnoses.hql
**Changes I made**
Currently the query that gets executed is : https://pastebin.com/rhPBFYmW . This gives an error in PostgreSQL:  https://pastebin.com/D9ZYPiXA . In order to get control of join I added the join part myself and not allowed hibernate to do it. 
After the change, the query that gets executed is : https://pastebin.com/t6gKAxuC 
Why change group by ? 
Because these fields were required in group by for PostgreSQL else you get an error. 
Will it effect the query ? 
o1.obsId will not as it is same as o.obsGroup 
o.encounter.encounterDatetime will not effect as it is unique of each obsId and encounterId.
I have tested the change on both MySQL and PostgreSQL and it is working fine.
**Link to ticket**
https://issues.openmrs.org/browse/EA-160
> EA-160 Error when entering recent visits in Reference Application on PostgreSQL

- fhir-condition/pom.xml
- fhir-condition/src/main/java/org/openmrs/module/fhir2conditions/api/dao/impl/FhirConditionDaoImpl.java
- fhir-condition/src/main/java/org/openmrs/module/fhir2conditions/api/impl/FhirConditionServiceImpl.java
- fhir-condition/src/main/java/org/openmrs/module/fhir2conditions/api/translators/impl/ConditionStatusTranslatorImpl.java
- fhir-condition/src/main/java/org/openmrs/module/fhir2conditions/api/translators/impl/ConditionTranslatorImpl.java
- fhir-condition/src/main/resources/moduleApplicationContext.xml
- fhir-condition/src/test/java/org/openmrs/module/fhir2conditions/api/impl/FhirConditionServiceImplTest.java
- fhir-condition/src/test/java/org/openmrs/module/fhir2conditions/api/translators/impl/ConditionStatusTranslatorImplTest.java
- fhir-condition/src/test/java/org/openmrs/module/fhir2conditions/api/translators/impl/ConditionTranslatorImplTest.java
- omod/pom.xml
- omod/src/main/resources/config.xml
- pom.xml
Issue worked on:
https://issues.openmrs.org/browse/EA-162
This PR adds support for FHIR conditions by:
- Adding mapping from EMR condition to FHIR condition (R4 & R3)
- Adds new Dao layer to support FHIR search operations
**NOTE**
In case someone wants to see this in action. I already uploaded `1.31.0-SNAPSHOT`of the EMR API module to the [openmrs-spa instance](https://openmrs-spa.org/openmrs).
> EA-162: Add support for FHIR condition resource

- api/src/main/java/org/openmrs/module/emrapi/utils/MetadataUtil.java
Ticket https://issues.openmrs.org/browse/EA-91
"EA-91: Remove MetadataUtil class from EMR API, removed the tests , and also removed the dependence on Metadasharing Module"
> EA-91: Deprecated MetadataUtil class in EMR API, 

- omod/src/main/java/org/openmrs/module/emrapi/web/rest/searchhandler/LastViewedPatientsSearchHandler.java
Issue: https://issues.openmrs.org/browse/EA-172
**Description:** 
Last viewed patients are displayed in "Find Patient Record" screen in the web client, however, these patients are saved in a table and displayed when needed. For other clients, e.g. Android, we will need the same. So, I suggest that we have a REST endpoint or query parameter to fetch the last viewed patients that we can use anywhere.
> EA-172: Add an API for fetching last viewed patients

- api-1.12/src/main/java/org/openmrs/module/emrapi/encounter/mapper/DosingInstructionsMapper.java
- api-1.12/src/main/java/org/openmrs/module/emrapi/encounter/mapper/OpenMRSDrugOrderMapper.java
- api-1.12/src/main/java/org/openmrs/module/emrapi/encounter/service/OrderMetadataService.java
- api-1.12/src/test/java/org/openmrs/module/emrapi/encounter/mapper/DosingInstructionsMapperTest.java
- api-1.12/src/test/java/org/openmrs/module/emrapi/encounter/service/OrderMetadataServiceTest.java
https://openmrs.atlassian.net/jira/software/c/projects/EA/issues/EA-179
> EA-179: Fix Locale issue while saving Medication

- api/src/main/java/org/openmrs/module/emrapi/encounter/domain/EncounterTransaction.java
Jira Card link - https://bahmni.atlassian.net/browse/BAH-3448?atlOrigin=eyJpIjoiYjZjZTNmOWRkMWJjNDY1ODhlZGI5YjViYWE4MzA5MzAiLCJwIjoiaiJ9
> BAH-3448 | Add. Accession number field in Order class

- api-1.12/src/test/java/org/openmrs/module/emrapi/encounter/mapper/DosingInstructionsMapperTest.java
Fixed the failing test of dosingInstructionMapper class
> EA-180 | Unable to save dosing instruction route in user locale. Test fix

- omod/src/main/resources/config.xml
Adds whitelist entries for the MetadataPackagesConfig classes supported by this module.
> TRUNK-6188: Add whitelisting for components loaded via XStream

- api/src/main/java/org/openmrs/module/emrapi/diagnosis/MigrateDiagnosis.java
- api/src/main/java/org/openmrs/module/emrapi/diagnosis/ObsGroupDiagnosisService.java
- api/src/main/resources/hql/patients_diagnoses.hql
- api/src/test/java/org/openmrs/module/emrapi/diagnosis/MigrateDiagnosisTest.java
Issue: https://openmrs.atlassian.net/browse/EA-216
This PR implement batch processing for patients - Diagnosis migration. Flush & clear the session after each batch.
> EA-216: Improve diagnosis migration performance for large datasets
