- api/src/main/resources/messages_de.properties
> EA-61: Create german messages.properties

- api-1.10/src/main/java/org/openmrs/module/emrapi/encounter/mapper/OrderMapper1_10.java
- api-1.11/src/main/java/org/openmrs/module/emrapi/encounter/mapper/OrderMapper1_11.java
- api/src/main/java/org/openmrs/module/emrapi/encounter/domain/EncounterTransaction.java
OrderType was missing in TestOrder. Fixed the same.
> EA-65: Fixed the bug that the OrderType is missing in TestOrder

- api-1.10/src/main/java/org/openmrs/module/emrapi/encounter/mapper/OpenMRSTestOrderMapper.java
- api-1.10/src/main/java/org/openmrs/module/emrapi/encounter/mapper/OrderMapper1_10.java
- api-1.10/src/test/java/org/openmrs/module/emrapi/encounter/EmrOrderServiceImpl_1_10Test.java
- api-1.10/src/test/java/org/openmrs/module/emrapi/encounter/builder/TestOrderBuilder.java
- api-1.10/src/test/java/org/openmrs/module/emrapi/encounter/mapper/OpenMRSTestOrderMapper1_10Test.java
- api-1.11/src/main/java/org/openmrs/module/emrapi/encounter/mapper/OpenMRSTestOrderMapper.java
- api-1.11/src/main/java/org/openmrs/module/emrapi/encounter/mapper/OrderMapper1_11.java
- api-1.11/src/test/java/org/openmrs/module/emrapi/encounter/EmrOrderServiceImpl_1_11Test.java
- api-1.11/src/test/java/org/openmrs/module/emrapi/encounter/builder/TestOrderBuilder.java
- api-1.11/src/test/java/org/openmrs/module/emrapi/encounter/mapper/OpenMRSTestOrderMapper1_11Test.java
- api/src/main/java/org/openmrs/module/emrapi/encounter/domain/EncounterTransaction.java
Please review the code.
https://issues.openmrs.org/browse/EA-72
> EA-72 | discontinuing test orders instead of voiding it.

- pom.xml
- tools/src/main/resources/eclipse/OpenMRSFormatter.xml
I'm doing this as one of the two modules required for GCI-11.
> Fixes GCI-11 Add formatter to pom

- api/src/main/java/org/openmrs/module/emrapi/encounter/EmrEncounterServiceImpl.java
- api/src/main/java/org/openmrs/module/emrapi/encounter/EncounterParameters.java
- api/src/main/java/org/openmrs/module/emrapi/encounter/matcher/DefaultEncounterMatcher.java
https://issues.openmrs.org/browse/EA-78
> EA-78 Changing encounter params to accept encounter uuid

- api-1.11/src/test/java/org/openmrs/module/emrapi/encounter/mapper/OpenMRSOrderMapper1_11Test.java
- api-1.12/pom.xml
- api-1.12/src/main/java/org/openmrs/module/emrapi/encounter/EmrOrderServiceImpl_1_12.java
- api-1.12/src/main/java/org/openmrs/module/emrapi/encounter/mapper/DosingInstructionsMapper.java
- api-1.12/src/main/java/org/openmrs/module/emrapi/encounter/mapper/DrugMapper1_12.java
- api-1.12/src/main/java/org/openmrs/module/emrapi/encounter/mapper/ObsMapper1_12.java
- api-1.12/src/main/java/org/openmrs/module/emrapi/encounter/mapper/OpenMRSDrugOrderMapper.java
- api-1.12/src/main/java/org/openmrs/module/emrapi/encounter/mapper/OpenMRSOrderMapper.java
- api-1.12/src/main/java/org/openmrs/module/emrapi/encounter/mapper/OrderMapper1_12.java
- api-1.12/src/main/java/org/openmrs/module/emrapi/encounter/service/OrderMetadataService.java
- api-1.12/src/main/resources/moduleApplicationContext.xml
- api-1.12/src/test/java/org/openmrs/module/emrapi/encounter/EmrOrderServiceImpl_1_12Test.java
- api-1.12/src/test/java/org/openmrs/module/emrapi/encounter/EncounterObservationServiceHelper1_12Test.java
- api-1.12/src/test/java/org/openmrs/module/emrapi/encounter/builder/DosingInstructionsBuilder.java
- api-1.12/src/test/java/org/openmrs/module/emrapi/encounter/builder/DrugOrderBuilder.java
- api-1.12/src/test/java/org/openmrs/module/emrapi/encounter/builder/OrderBuilder.java
- api-1.12/src/test/java/org/openmrs/module/emrapi/encounter/mapper/DosingInstructionsMapperTest.java
- api-1.12/src/test/java/org/openmrs/module/emrapi/encounter/mapper/OpenMRSDrugOrderMapper1_12Test.java
- api-1.12/src/test/java/org/openmrs/module/emrapi/encounter/mapper/OpenMRSOrderMapper_1_12_Test.java
- api-1.12/src/test/java/org/openmrs/module/emrapi/encounter/mapper/OrderMapper1_12Test.java
- api-1.12/src/test/java/org/openmrs/module/emrapi/encounter/service/OrderMetadataServiceTest.java
- api/src/main/java/org/openmrs/module/emrapi/encounter/domain/EncounterTransaction.java
- omod/pom.xml
- omod/src/main/resources/config.xml
- pom.xml
Created new module emrapi-1.12
Switching emrapi to 1.13-SNAPSHOT
> EA-85 : Providing ability for Free text drug ordering

- api/src/main/java/org/openmrs/module/emrapi/encounter/EncounterProviderMapper.java
- api/src/test/java/org/openmrs/module/emrapi/encounter/EncounterProviderMapperTest.java
Reference :- https://issues.openmrs.org/browse/EA-90
> EA:90 Adding null check for encounterRole for a provider

- omod/src/main/java/org/openmrs/module/emrapi/rest/resource/PatientProfileResource.java
- omod/src/main/java/org/openmrs/module/emrapi/rest/resource/PersonImageResource.java
Changed the excetion message to include delete forever instead of purge
> Fix for TRUNK-2299

- api-1.12/src/main/java/org/openmrs/module/emrapi/encounter/EmrOrderServiceImpl_1_12.java
- api-1.12/src/main/java/org/openmrs/module/emrapi/encounter/mapper/OpenMRSOrderGroupMapper.java
- api-1.12/src/main/java/org/openmrs/module/emrapi/encounter/mapper/OrderMapper1_12.java
- api-1.12/src/main/resources/moduleApplicationContext.xml
- api-1.12/src/test/java/org/openmrs/module/emrapi/encounter/EmrOrderServiceImpl_1_12Test.java
- api-1.12/src/test/java/org/openmrs/module/emrapi/encounter/builder/OrderBuilder.java
- api-1.12/src/test/java/org/openmrs/module/emrapi/encounter/mapper/OrderMapper1_12Test.java
- api/src/main/java/org/openmrs/module/emrapi/encounter/domain/EncounterTransaction.java
- omod/pom.xml
Added OrderGroup to EncounterTranscation
Saving Orders which are a prat of an OrderGroup when encounter is saved.
> EA_94 - OrderSet Story Implementation

- omod/src/main/resources/config.xml
see https://issues.openmrs.org/browse/EA-95
> EA-95 Add missing global property emr.encounterMatcher to config.xml

- api-1.12/src/main/java/org/openmrs/module/emrapi/encounter/mapper/OpenMRSDrugOrderMapper.java
- api-1.12/src/main/java/org/openmrs/module/emrapi/encounter/mapper/OrderMapper1_12.java
- api/src/main/java/org/openmrs/module/emrapi/encounter/domain/EncounterTransaction.java
Exposed sortWeight field, so that clients can set the sortWeights
> EA-97 | SortWeight For Orders In OrderGroups:

- api/src/main/java/org/openmrs/module/emrapi/adt/AdtServiceImpl.java
- api/src/main/java/org/openmrs/module/emrapi/visit/EmrVisitServiceImpl.java
- api/src/test/java/org/openmrs/module/emrapi/adt/AdtServiceComponentTest.java
- api/src/test/java/org/openmrs/module/emrapi/adt/AdtServiceTest.java
- api/src/test/resources/visitLocationDataSetup.xml
As part of 'Close Stale Visits Task' we are closing the following visits
1. which do not have location tagged to it.(location_id is null)
2. which have visit location tagged to it.
> EA-101  Considering visit location while closing stale visits

- api/src/main/java/org/openmrs/module/emrapi/encounter/EncounterDispositionServiceHelper.java
- api/src/test/java/org/openmrs/module/emrapi/encounter/EncounterDispositionServiceHelperTest.java
- omod/src/test/java/org/openmrs/module/emrapi/web/controller/EmrEncounterController_1_11_Test.java
new disposition will now have current dateTime as dispositionDateTime instead of encounterDateTime
> EA-113 | new disposition will now have current dateTime as dispositionDateTime

- .travis.yml
- api/src/main/java/org/openmrs/module/emrapi/adt/AdtServiceImpl.java
- api/src/main/java/org/openmrs/module/emrapi/db/EmrVisitDAO.java
- api/src/main/java/org/openmrs/module/emrapi/db/EmrVisitDAOImpl.java
- api/src/main/java/org/openmrs/module/emrapi/diagnosis/Diagnosis.java
- api/src/main/java/org/openmrs/module/emrapi/domainwrapper/DomainWrapperFactory.java
- api/src/main/java/org/openmrs/module/emrapi/patient/PatientDomainWrapper.java
- api/src/main/java/org/openmrs/module/emrapi/visit/EmrVisitService.java
- api/src/main/java/org/openmrs/module/emrapi/visit/EmrVisitServiceImpl.java
- api/src/main/java/org/openmrs/module/emrapi/visit/VisitDomainWrapper.java
- api/src/main/resources/hql/visit_confirmed_diagnoses.hql
- api/src/main/resources/hql/visit_diagnoses.hql
- api/src/main/resources/hql/visit_primary_diagnoses.hql
- api/src/main/resources/moduleApplicationContext.xml
- api/src/test/java/org/openmrs/module/emrapi/patient/PatientDomainWrapperTest.java
- api/src/test/java/org/openmrs/module/emrapi/visit/VisitDomainWrapperComponentTest.java
- api/src/test/java/org/openmrs/module/emrapi/visit/VisitDomainWrapperTest.java
Same as https://github.com/openmrs/openmrs-module-emrapi/pull/110 but for this new 1.12.x branch.
> EA-114: 3 out of 4 getUniqueDiagnoses(..) cases re-implemented with HQL.

- api/src/main/java/org/openmrs/module/emrapi/db/EmrVisitDAOImpl.java
- api/src/main/java/org/openmrs/module/emrapi/visit/VisitDomainWrapper.java
- api/src/main/resources/hql/visit_confirmed_primary_diagnoses.hql
Same for the new 1.12.x branch.
> EA-114: getUniqueDiagnoses(true, true) reimplemented with HQL.

- api/src/main/resources/hql/visit_confirmed_diagnoses.hql
- api/src/main/resources/hql/visit_confirmed_primary_diagnoses.hql
- api/src/main/resources/hql/visit_diagnoses.hql
- api/src/main/resources/hql/visit_primary_diagnoses.hql
As per @lluismf suggestion here https://talk.openmrs.org/t/core-apps-very-long-ttfb-for-patientdashboard-page-when-many-encounters/8597/34?u=mksd
modified:   api/src/main/resources/hql/visit_confirmed_diagnoses.hql
modified:   api/src/main/resources/hql/visit_confirmed_primary_diagnoses.hql
modified:   api/src/main/resources/hql/visit_diagnoses.hql
modified:   api/src/main/resources/hql/visit_primary_diagnoses.hql
> EA-114: Simplifying HQL queries.

- api/src/main/java/org/openmrs/module/emrapi/EmrApiConstants.java
- api/src/main/java/org/openmrs/module/emrapi/adt/EmrApiVisitAssignmentHandler.java
- api/src/main/java/org/openmrs/module/emrapi/adt/EncounterTypetoVisitTypeMapper.java
- api/src/main/resources/moduleApplicationContext.xml
- api/src/test/java/org/openmrs/module/emrapi/adt/EmrApiVisitAssignmentHandlerTest.java
- api/src/test/java/org/openmrs/module/emrapi/adt/EncounterTypeToVisitTypeMapperTest.java
- omod/src/main/resources/config.xml
@dkayiwa  I am running into a  strange error with the test in this case. The visit service is not available as its called the stack trace is https://gist.github.com/ssmusoke/5c1bce5b520d5e140a1ca5e3595f8cdf
> EA-116 - Adding an encounter without a prior visit

- omod/src/main/java/org/openmrs/module/emrapi/rest/resource/PatientProfileResource.java
- omod/src/main/java/org/openmrs/module/emrapi/rest/resource/PersonImageResource.java
Added 2.1.* to all resources in emrapi
> EA-120 Upgrade openmrs version in resources in emr api to support 2.1.*

- condition-list/src/main/java/org/openmrs/module/emrapi/conditionslist/contract/Concept.java
- condition-list/src/main/java/org/openmrs/module/emrapi/conditionslist/contract/ConditionMapper.java
- condition-list/src/test/java/org/openmrs/module/emrapi/conditionslist/contract/ConditionMapperTest.java
* Added 'shortName' and 'name' properties to conditionslist.contract.concept
> EA-122 | Conditions List implementation

- condition-list/src/main/java/org/openmrs/module/emrapi/conditionslist/impl/ConditionServiceImpl.java
- condition-list/src/test/java/org/openmrs/module/emrapi/conditionslist/impl/ConditionServiceImplTest.java
https://issues.openmrs.org/browse/EA-123
> EA-123| Fix wrong endDate on condition status changed

- omod/src/main/java/org/openmrs/module/emrapi/web/controller/DiagnosisController.java
Issue: https://issues.openmrs.org/browse/EA-125
> [EA-125] Add a "diagnosis" REST resource

- omod/src/main/java/org/openmrs/module/emrapi/web/controller/EmrConceptSearchController.java
- omod/src/test/java/org/openmrs/module/emrapi/web/controller/EmrConceptSearchControllerTest.java
- omod/src/test/resources/diagnosisMetaData.xml
https://issues.openmrs.org/browse/EA-131
> EA-131| EmrConceptSearchController should allow search by concept reference term code

- api-2.2/pom.xml
- omod/pom.xml
- omod/src/main/resources/config.xml
- pom.xml
[TRUNK-5345: Refactor ConditionService to use new functionality](https://issues.openmrs.org/browse/TRUNK-5345)
Refactor emrapi module's ConditionService to use this new functionality under the hood (e.g. either delegating to openmrs-core, or using the current emrapi approach, depending on the openmrs-core version)
> TRUNK-5345: Refactor ConditionService to use new functionality (Work In Progress)

- api/src/main/java/org/openmrs/module/emrapi/EmrApiActivator.java
- api/src/main/java/org/openmrs/module/emrapi/EmrApiConstants.java
- api/src/main/java/org/openmrs/module/emrapi/EmrApiProperties.java
- api/src/test/java/org/openmrs/module/emrapi/EmrApiActivatorComponentTest.java
see topic in security mailing list
> Fix excessive privilege issue

- api/src/main/java/org/openmrs/module/emrapi/diagnosis/DiagnosisService.java
- api/src/main/java/org/openmrs/module/emrapi/diagnosis/DiagnosisServiceImpl.java
Deprecate diagnosis service methods in the emrapi module
see https://issues.openmrs.org/browse/TRUNK-5342
No? -> [read here](https://wiki.openmrs.org/display/docs/Pull+Request+Tips) on how to squash multiple commits into one
No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Your+IDE), format the code and add the changes with `git add . && git commit --amend`
No? -> write tests and add them to this commit `git add . && git commit --amend`
No? -> execute above command
No? -> figure out why and add the fix to your commit. It is your responsibility to make sure your code works.
No? Unsure? …
> TRUNK-5342: Deprecate diagnosis service methods in the emrapi module

- api/src/main/java/org/openmrs/module/emrapi/diagnosis/Diagnosis.java
The PR adds existingDiagnosis property to diagnosis class.
see https://issues.openmrs.org/browse/TRUNK-5343
> TRUNK-5343: Add existingDiagnosis property to diagnosis class.

- api/src/main/java/org/openmrs/module/emrapi/EmrApiProperties.java
- api/src/main/java/org/openmrs/module/emrapi/concept/HibernateEmrConceptDAO.java
- api/src/test/java/org/openmrs/module/emrapi/EmrApiPropertiesTest.java
- omod/src/main/java/org/openmrs/module/emrapi/web/controller/EmrConceptSearchController.java
- omod/src/test/java/org/openmrs/module/emrapi/web/controller/BaseEmrControllerTest.java
- omod/src/test/java/org/openmrs/module/emrapi/web/controller/EmrConceptSearchControllerTest.java
https://issues.openmrs.org/browse/EA-136?filter=-1
> EA-136: Handling concept searching when ConceptSource is null

- api/src/test/java/org/openmrs/module/emrapi/adt/AdtServiceComponentTest.java
Issue : https://issues.openmrs.org/browse/EA-141
> Added @Ignore attribute to randomly failing test

- condition-list/src/main/java/org/openmrs/module/emrapi/conditionslist/contract/ConditionMapper.java
Fixed the bug which prevented the condition from being saved.
see https://issues.openmrs.org/browse/EA-150
No? -> [read here](https://wiki.openmrs.org/display/docs/Pull+Request+Tips) on how to squash multiple commits into one
No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Your+IDE), format the code and add the changes with `git add . && git commit --amend`
No? -> write tests and add them to this commit `git add . && git commit --amend`
No? -> execute above command
No? -> figure out why and add the fix to your commit. It is your responsibility to make sure your code works.
No? Unsure? …
> EA-150: Fixed error while saving condition

- .travis.yml
- web-2.2/src/main/java/org/openmrs/module/emrapi/web/controller/ConditionController.java
- web-pre2.2/src/main/java/org/openmrs/module/emrapi/web/controller/ConditionController.java
Added the functionality to edit an existing condition.
Related PR: https://github.com/openmrs/openmrs-module-coreapps/pull/192
see https://issues.openmrs.org/browse/RA-1526
No? -> [read here](https://wiki.openmrs.org/display/docs/Pull+Request+Tips) on how to squash multiple commits into one
No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Your+IDE), format the code and add the changes with `git add . && git commit --amend`
No? -> write tests and add them to this commit `git add . && git commit --amend`
No? -> execute above command
No? -> figure out why and add the fix to your commit. It …
> RA-1526: Edit Conditions

- web-2.2/src/main/java/org/openmrs/module/emrapi/web/controller/ConditionController.java
Fix error while saving condition
see https://issues.openmrs.org/browse/RA-1488
No? -> [read here](https://wiki.openmrs.org/display/docs/Pull+Request+Tips) on how to squash multiple commits into one
No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Your+IDE), format the code and add the changes with `git add . && git commit --amend`
No? -> write tests and add them to this commit `git add . && git commit --amend`
No? -> execute above command
No? -> figure out why and add the fix to your commit. It is your responsibility to make sure your code works.
No? Unsure? -> execute command `git pull …
> RA-1488: Error while saving condition

- omod/src/main/java/org/openmrs/module/emrapi/rest/resource/PatientProfileResource.java
- omod/src/main/java/org/openmrs/module/emrapi/rest/resource/PersonImageResource.java
- omod/src/main/resources/config.xml
**Issue worked on:** https://issues.openmrs.org/browse/EA-152
> EA-152: Support openmrs platform 2.2.x, 2.3.x and 2.4.x

- api/src/main/java/org/openmrs/module/emrapi/account/AccountDomainWrapper.java
- api/src/main/java/org/openmrs/module/emrapi/account/AccountValidator.java
- api/src/main/java/org/openmrs/module/emrapi/adt/AdtServiceImpl.java
- api/src/main/java/org/openmrs/module/emrapi/concept/HibernateEmrConceptDAO.java
- api/src/main/java/org/openmrs/module/emrapi/patient/PatientDomainWrapper.java
- api/src/main/java/org/openmrs/module/emrapi/test/builder/ConceptBuilder.java
- api/src/main/java/org/openmrs/module/emrapi/utils/GeneralUtils.java
- api/src/main/java/org/openmrs/module/emrapi/utils/ModuleProperties.java
- api/src/test/java/org/openmrs/module/emrapi/EmrApiPropertiesTest.java
Jira Issue: https://issues.openmrs.org/browse/GCI-323
I also simplified a ternary expression in the process.
> [GCI-323] Replace size() == 0 with isEmpty()

- api/src/main/java/org/openmrs/module/emrapi/adt/AdtServiceImpl.java
**Issue worked on:** https://issues.openmrs.org/browse/EA-12
> EA-12: Allow PatientMergeActions to be lazy-autowired

- api/src/main/java/org/openmrs/module/emrapi/EmrApiActivator.java
https://issues.openmrs.org/browse/MAP-19
> MAP-19: Set UUID on existing extra patient identifier types metadata set.

- api/src/main/java/org/openmrs/module/emrapi/disposition/Disposition.java
- api/src/main/java/org/openmrs/module/emrapi/disposition/DispositionService.java
- api/src/main/java/org/openmrs/module/emrapi/disposition/DispositionServiceImpl.java
- api/src/test/java/org/openmrs/module/emrapi/disposition/DispositionServiceTest.java
- api/src/test/resources/specifiedDispositionConfig.json
Adds support for filtering dispositions based on the EncounterType.
> RA-1770: Allow dispositions to be filtered based on EncounterType

- api/src/main/java/org/openmrs/module/emrapi/EmrApiActivator.java
- api/src/main/java/org/openmrs/module/emrapi/disposition/DispositionServiceImpl.java
https://issues.openmrs.org/browse/EA-158
> EA-158: Allow loading disposition configs from file system

- api/src/main/java/org/openmrs/module/emrapi/EmrApiConstants.java
- omod/src/test/resources/diagnosisMetaData.xml
Reverts openmrs/openmrs-module-emrapi#187
> Revert "EA-159 Correct EMR Api Constants to make them consistent with db"

- api/src/main/resources/hql/patients_diagnoses.hql
**Changes I made**
Set voided = 0 to voided = false.
**Link to ticket**
https://issues.openmrs.org/browse/EA-161
> EA-161 Set voided = false in EMR Api hql files

- pom.xml
This should hopefully fix failing builds on Bamboo
> Update to event-api-2.8.0

- .travis.yml
- api/src/main/java/org/openmrs/module/emrapi/encounter/EmrEncounterServiceImpl.java
- api/src/test/java/org/openmrs/module/emrapi/encounter/EmrEncounterServiceTest.java
https://issues.openmrs.org/browse/EA-163
Added condition to ignore `saveVisit()` for the existing visit.
> EA-163: Add condition to bypass saveVisit() when existing visit.

- fhir-condition/pom.xml
- fhir-condition/src/main/java/org/openmrs/module/emrapi/fhircondition/api/dao/impl/FhirConditionDaoImpl.java
- fhir-condition/src/main/java/org/openmrs/module/emrapi/fhircondition/api/impl/FhirConditionServiceImpl.java
- fhir-condition/src/main/java/org/openmrs/module/emrapi/fhircondition/api/translators/impl/ConditionStatusTranslatorImpl.java
- fhir-condition/src/main/java/org/openmrs/module/emrapi/fhircondition/api/translators/impl/ConditionTranslatorImpl.java
- fhir-condition/src/test/java/org/openmrs/module/emrapi/fhircondition/api/impl/FhirConditionServiceImplTest.java
- fhir-condition/src/test/java/org/openmrs/module/emrapi/fhircondition/api/translators/impl/ConditionStatusTranslatorImplTest.java
- fhir-condition/src/test/java/org/openmrs/module/emrapi/fhircondition/api/translators/impl/ConditionTranslatorImplTest.java
**Issue worked on:**
https://issues.openmrs.org/browse/EA-164
**Changes**
- Adds support to create and update conditions
- Renamed the package
> EA-164: Add support to create, and update FHIR condition

- web-2.2/src/main/java/org/openmrs/module/emrapi/web/controller/ConditionController.java
See comments on core PR:
https://github.com/openmrs/openmrs-core/pull/4290
> TRUNK-6171 - Fix to emrapi condition conversion

- api/src/main/java/org/openmrs/module/emrapi/adt/AdtServiceImpl.java
- api/src/main/java/org/openmrs/module/emrapi/adt/InpatientAdmission.java
- api/src/test/java/org/openmrs/module/emrapi/adt/AdtServiceImplTest.java
- omod/src/main/java/org/openmrs/module/emrapi/rest/converter/InpatientAdmissionConverter.java
See:  https://openmrs.atlassian.net/browse/EA-200
> EA-200 - add InpatientRequest to EMR API Inpatient Admission

- api/src/main/java/org/openmrs/module/emrapi/adt/AdtServiceImpl.java
See https://openmrs.atlassian.net/browse/EA-195
> EA-195 - ADT inpatient requests should be fulfilled by any ADT encounter
